# Site settings
title: My libcxx stuff
email: admin@efcs.ca
description: My First Site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://libcxx.efcs.ca" # the base hostname & protocol for your site

# Build settings
#markdown: kramdown

